/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/category/[category]': RouteRecordInfo<'/category/[category]', '/category/:category', { category: ParamValue<true> }, { category: ParamValue<false> }>,
    '/contact-us': RouteRecordInfo<'/contact-us', '/contact-us', Record<never, never>, Record<never, never>>,
    '/delivery-policy': RouteRecordInfo<'/delivery-policy', '/delivery-policy', Record<never, never>, Record<never, never>>,
    '/help-faqs': RouteRecordInfo<'/help-faqs', '/help-faqs', Record<never, never>, Record<never, never>>,
    '/order-history': RouteRecordInfo<'/order-history', '/order-history', Record<never, never>, Record<never, never>>,
    '/quick-start': RouteRecordInfo<'/quick-start', '/quick-start', Record<never, never>, Record<never, never>>,
    '/returns': RouteRecordInfo<'/returns', '/returns', Record<never, never>, Record<never, never>>,
    '/store/[...id]': RouteRecordInfo<'/store/[...id]', '/store/:id(.*)', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/track-order': RouteRecordInfo<'/track-order', '/track-order', Record<never, never>, Record<never, never>>,
  }
}
